[tool.poetry]
name = "pydantic-v2-essentials"
version = "0.1.0"
description = ""
authors = ["diego <diegoinsights@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
